services:
  webprefs:
    image: tacticallaptopbag/webprefs
    build: https://github.com/TacticalLaptopBag/webprefs.git
    restart: unless-stopped
    environment:
      # It is recommended you change this to a comma-separated list of origins
      # you will use to access this service
      - CORS_ALLOWED_ORIGINS=*
      # You should absolutely change this to a very long password (>=40 chars).
      # Otherwise, your installation will be very insecure
      - JWT_SECRET=debug-key

      # How long before a login token expires
      - JWT_EXPIRY_SECONDS=900
      # How long before a refresh token expires
      - JWT_REFRESH_EXPIRY_SECONDS=604800
      # Uncomment this line to disable hosting any web frontend.
      #- APP_SERVE_PATH=
    volumes:
      - webprefs-data:/app/data
      # If you want to host your webapp using webprefs' backend,
      # uncomment this line and point this to your webapp's files
      # - ./frontend:/app/web
    ports:
      # Change 8080 to the port you want to use to connect to webprefs
      - 8080:80

volumes:
  webprefs-data:
